### ISSUE TITLE
Unable to scroll vertically on webpage

### ISSUE THREAD

**Issue by bigbeno37** [corysimmons/boy#19]
I'm using Chrome Version 43.0.2357.132 m and after implementing this template, I am no longer able to scroll vertically using the scroll wheel. 

After doing some research, I deduced that it was due to reset.css's overflow properties. I deleted those properties, and the webpage is again scrollable. However, if reset.css causes this to happen, then those specific overflow properties should be removed from Boy to prevent further issues.

**Comment by corysimmons** [comment]
Yeah I need to fix this. Care to submit a PR?

**Comment by corysimmons** [comment]
I've removed anything that could be tripping up overflow stuff. The only overflow thing I'm touching now is `overflow-y: scroll` on `body` (to produce a vertical scrollbar).

**Comment by corysimmons** [comment]
I can't replicate but I'll keep an eye out for this thing. I've bumped into it before. I originally added it for some flexbox specific reason but it's more trouble than it's worth. I think we're safe now.
