### ISSUE TITLE
Jade

### ISSUE THREAD

**Issue by antoniobrandao** [corysimmons/boy#3]
Would be great if this was available in Jade. 

For those of us who like to use "dry" syntax everywhere :) I'm working with Jeet using Stylus & Jade. Would be great to just throw in this boilerplate but I'll have to convert.

Just a suggestion !

**Comment by corysimmons** [comment]
@antoniobrandao I removed the conditional classes from the `html` elem but I'm still closing this. It would probably be best for any versions of this (Jade, Haml, Slim, etc.) to be in their own repo instead of people having to pull in those versions every time they want a pure html version.
