### ISSUE TITLE
Change <!--[if lt IE 10]> to <!--[if IE]>

### ISSUE THREAD

**Issue by QWp6t** [corysimmons/boy#6]
See: https://github.com/corysimmons/boy/blob/master/index.html#L15-L21

IE 10 does not support conditional comments. It is therefore unnecessary to specify version number here since the condition is always true for all versions below IE 10 regardless of whether a version is specified.

**Comment by corysimmons** [comment]
Fixed https://github.com/corysimmons/boy/commit/25edf7e12271ed5f6e4c63cc13ecec888f1f7443

Thanks for pointing this out.
