### ISSUE TITLE
Mistakes

### ISSUE THREAD

**Issue by wolffe** [corysimmons/boy#7]
1. Why support IE6 beyond its end-of-life period?
2. Why support IE7?
3. Why @import CSS? It's bad practice.

**Comment by corysimmons** [comment]
Some people still use IE6, but this boilerplate doesn't specifically aim to support IE6 by any means. All the polyfills target IE6**-8** and [quite a few people](http://gs.statcounter.com/#desktop-browser_version-ww-monthly-201402-201502-bar) still use IE8. In fact, this boilerplate is unique in that it supports people who still develop for those browsers. All polyfills are conditionally loaded so they only download to browsers that actually need them. This makes it a seamless integration.

Why is `@import` bad practice? I've never heard of this.

**Comment by wolffe** [comment]
@import is bad practice because, in short, you are calling a CSS file which calls another CSS file. This is redundant, why not call directly the intended stylesheet?

Also, IE8 is still being used and it's our job to not target it so that more and more users switch browsers or upgrade.

Even if all polyfills are conditionally loaded, they are still there, contributing to the weight of the project. I'd rather have a lightweight project targeting best practices and modern browsers than a mammoth targeting everything.

But I do understand where you're coming from.

**Comment by corysimmons** [comment]
- I disagree about the `@import` being a bad practice. 1) It cuts down on HTTP requests to `@import` other stylesheets 2) It keeps Normalize.css virgin source for easy updating 3) It doesn't clutter `style.css` with multiple `@import` statements that are effectively doing the same thing.
- I don't specifically develop for IE8, and I'm sure most of my sites look atrocious in it, but they'd look even more atrocious if I didn't use this boilerplate. At least this way they get some semblance of the site and it doesn't cost me any extra work to do.
- Maybe https://html5boilerplate.com is a better fit for you. Boy is built off of it so it does all the nice things H5BP does, but also supports older browsers for free. If neither of these projects is exactly what you're looking for, feel free to create your own boilerplate?
- I understand where you're coming from too, but honestly, this is a lighter version of H5BP and it provides a little **free** support for older browsers without ensuring IE8 lives another 6 years. I guess I just don't agree with your qualms with it.

**Comment by wolffe** [comment]
No worries. Great job, anyway.

**Comment by corysimmons** [comment]
Thanks for the support.
